import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

export const supabase = createClient(supabaseUrl, supabaseAnonKey)

export type Database = {
  public: {
    Tables: {
      feedback: {
        Row: {
          id: string
          assessment_id: string
          title: string
          rating: 'positive' | 'negative'
          comment: string | null
          timestamp: string
          user_id: string
          item_data: any
          deleted_at: string | null
          deleted_by: string | null
        }
        Insert: {
          id?: string  // Auto-generated by database
          assessment_id: string
          title: string
          rating: 'positive' | 'negative'
          comment?: string | null
          timestamp?: string
          user_id: string
          item_data: any
          deleted_at?: string | null
          deleted_by?: string | null
        }
        Update: {
          id?: string
          assessment_id?: string
          title?: string
          rating?: 'positive' | 'negative'
          comment?: string | null
          timestamp?: string
          user_id?: string
          item_data?: any
          deleted_at?: string | null
          deleted_by?: string | null
        }
      }
    }
  }
} 